include_files = [
('C:/WINDOWS/SYSTEM32/ntdll.dll', 'ntdll.dll'),
('C:/WINDOWS/System32/KERNELBASE.dll', 'KERNELBASE.dll'),
('C:/WINDOWS/System32/msvcrt.dll', 'msvcrt.dll'),
('c:/msys64/mingw64/bin/libpython3.9.dll', 'libpython3.9.dll'),
('C:/WINDOWS/System32/ADVAPI32.dll', 'ADVAPI32.dll'),
('C:/WINDOWS/System32/sechost.dll', 'sechost.dll'),
('C:/WINDOWS/System32/RPCRT4.dll', 'RPCRT4.dll'),
('C:/WINDOWS/System32/SHLWAPI.dll', 'SHLWAPI.dll'),
('C:/WINDOWS/System32/WS2_32.dll', 'WS2_32.dll'),
('C:/WINDOWS/SYSTEM32/VERSION.dll', 'VERSION.dll'),
('C:/WINDOWS/SYSTEM32/CRYPTSP.dll', 'CRYPTSP.dll'),
('C:/WINDOWS/system32/rsaenh.dll', 'rsaenh.dll'),
('C:/WINDOWS/System32/bcrypt.dll', 'bcrypt.dll'),
('C:/WINDOWS/SYSTEM32/CRYPTBASE.dll', 'CRYPTBASE.dll'),
('C:/WINDOWS/System32/bcryptPrimitives.dll', 'bcryptPrimitives.dll'),
('C:/Program Files/Git/mingw64/bin/zlib1.dll', 'zlib1.dll'),
('C:/Program Files/Git/mingw64/bin/libbz2-1.dll', 'libbz2-1.dll'),
('C:/Program Files/Git/mingw64/bin/liblzma-5.dll', 'liblzma-5.dll'),
('C:/Program Files/Git/mingw64/bin/libssl-1_1-x64.dll', 'libssl-1_1-x64.dll'),
('C:/Program Files/Git/mingw64/bin/libcrypto-1_1-x64.dll', 'libcrypto-1_1-x64.dll'),
('C:/WINDOWS/System32/USER32.dll', 'USER32.dll'),
('C:/WINDOWS/System32/win32u.dll', 'win32u.dll'),
('C:/WINDOWS/System32/GDI32.dll', 'GDI32.dll'),
('C:/WINDOWS/System32/gdi32full.dll', 'gdi32full.dll'),
('C:/WINDOWS/System32/msvcp_win.dll', 'msvcp_win.dll'),
('C:/WINDOWS/System32/ucrtbase.dll', 'ucrtbase.dll'),
('C:/WINDOWS/system32/mswsock.dll', 'mswsock.dll'),
('C:/msys64/mingw64/bin/libmpdec-2.dll', 'libmpdec-2.dll'),
('C:/Program Files/Git/mingw64/bin/libgcc_s_seh-1.dll', 'libgcc_s_seh-1.dll'),
('C:/Program Files/Git/mingw64/bin/libwinpthread-1.dll', 'libwinpthread-1.dll'),
('C:/WINDOWS/SYSTEM32/ntdll.dll', 'ntdll.dll'),
('C:/WINDOWS/System32/KERNELBASE.dll', 'KERNELBASE.dll'),
('C:/WINDOWS/System32/msvcrt.dll', 'msvcrt.dll'),
('C:/msys64/mingw64/bin/libpython3.9.dll', 'libpython3.9.dll'),
('C:/WINDOWS/System32/ADVAPI32.dll', 'ADVAPI32.dll'),
('C:/WINDOWS/System32/sechost.dll', 'sechost.dll'),
('C:/WINDOWS/System32/RPCRT4.dll', 'RPCRT4.dll'),
('C:/WINDOWS/System32/SHLWAPI.dll', 'SHLWAPI.dll'),
('C:/WINDOWS/System32/WS2_32.dll', 'WS2_32.dll'),
('C:/WINDOWS/SYSTEM32/VERSION.dll', 'VERSION.dll'),
('C:/WINDOWS/SYSTEM32/CRYPTSP.dll', 'CRYPTSP.dll'),
('C:/WINDOWS/system32/rsaenh.dll', 'rsaenh.dll'),
('C:/WINDOWS/System32/bcrypt.dll', 'bcrypt.dll'),
('C:/WINDOWS/SYSTEM32/CRYPTBASE.dll', 'CRYPTBASE.dll'),
('C:/WINDOWS/System32/bcryptPrimitives.dll', 'bcryptPrimitives.dll'),
('C:/Program Files/Git/mingw64/bin/libffi-7.dll', 'libffi-7.dll'),
('C:/msys64/mingw64/bin/libgobject-2.0-0.dll', 'libgobject-2.0-0.dll'),
('C:/msys64/mingw64/bin/libglib-2.0-0.dll', 'libglib-2.0-0.dll'),
('C:/msys64/mingw64/bin/libgirepository-1.0-1.dll', 'libgirepository-1.0-1.dll'),
('C:/WINDOWS/System32/ole32.dll', 'ole32.dll'),
('C:/WINDOWS/System32/ucrtbase.dll', 'ucrtbase.dll'),
('C:/WINDOWS/System32/combase.dll', 'combase.dll'),
('C:/WINDOWS/System32/GDI32.dll', 'GDI32.dll'),
('C:/WINDOWS/System32/win32u.dll', 'win32u.dll'),
('C:/WINDOWS/System32/gdi32full.dll', 'gdi32full.dll'),
('C:/WINDOWS/System32/msvcp_win.dll', 'msvcp_win.dll'),
('C:/WINDOWS/System32/USER32.dll', 'USER32.dll'),
('C:/WINDOWS/System32/SHELL32.dll', 'SHELL32.dll'),
('C:/Program Files/Git/mingw64/bin/libintl-8.dll', 'libintl-8.dll'),
('C:/msys64/mingw64/bin/libgio-2.0-0.dll', 'libgio-2.0-0.dll'),
('C:/msys64/mingw64/bin/libgmodule-2.0-0.dll', 'libgmodule-2.0-0.dll'),
('C:/Program Files/Git/mingw64/bin/libwinpthread-1.dll', 'libwinpthread-1.dll'),
('C:/WINDOWS/SYSTEM32/DNSAPI.dll', 'DNSAPI.dll'),
('C:/Program Files/Git/mingw64/bin/libpcre-1.dll', 'libpcre-1.dll'),
('C:/Program Files/Git/mingw64/bin/libiconv-2.dll', 'libiconv-2.dll'),
('C:/Program Files/Git/mingw64/bin/zlib1.dll', 'zlib1.dll'),
('C:/WINDOWS/System32/NSI.dll', 'NSI.dll'),
('C:/msys64/mingw64/bin/libcairo-2.dll', 'libcairo-2.dll'),
('C:/WINDOWS/SYSTEM32/MSIMG32.dll', 'MSIMG32.dll'),
('C:/msys64/mingw64/bin/libcairo-gobject-2.dll', 'libcairo-gobject-2.dll'),
('C:/Program Files/Git/mingw64/bin/libgcc_s_seh-1.dll', 'libgcc_s_seh-1.dll'),
('C:/msys64/mingw64/bin/libfontconfig-1.dll', 'libfontconfig-1.dll'),
('C:/msys64/mingw64/bin/libfreetype-6.dll', 'libfreetype-6.dll'),
('C:/msys64/mingw64/bin/libpng16-16.dll', 'libpng16-16.dll'),
('C:/msys64/mingw64/bin/libpixman-1-0.dll', 'libpixman-1-0.dll'),
('C:/Program Files/Git/mingw64/bin/libexpat-1.dll', 'libexpat-1.dll'),
('C:/Program Files/Git/mingw64/bin/libbz2-1.dll', 'libbz2-1.dll'),
('C:/Program Files/Git/mingw64/bin/libbrotlidec.dll', 'libbrotlidec.dll'),
('C:/msys64/mingw64/bin/libharfbuzz-0.dll', 'libharfbuzz-0.dll'),
('C:/Program Files/Git/mingw64/bin/libbrotlicommon.dll', 'libbrotlicommon.dll'),
('C:/WINDOWS/SYSTEM32/USP10.dll', 'USP10.dll'),
('C:/Program Files/Git/mingw64/bin/libstdc++-6.dll', 'libstdc++-6.dll'),
('C:/msys64/mingw64/bin/libgraphite2.dll', 'libgraphite2.dll'),
('C:/Program Files/Git/mingw64/bin/libgmp-10.dll', 'libgmp-10.dll'),
('C:/Program Files/Git/mingw64/bin/liblzma-5.dll', 'liblzma-5.dll'),
('C:/msys64/mingw64/bin/libmpdec-2.dll', 'libmpdec-2.dll'),
('C:/msys64/mingw64/bin/libpango-1.0-0.dll', 'libpango-1.0-0.dll'),
('C:/msys64/mingw64/bin/libthai-0.dll', 'libthai-0.dll'),
('C:/msys64/mingw64/bin/libfribidi-0.dll', 'libfribidi-0.dll'),
('C:/msys64/mingw64/bin/libdatrie-1.dll', 'libdatrie-1.dll'),
('C:/msys64/mingw64/bin/libgdk_pixbuf-2.0-0.dll', 'libgdk_pixbuf-2.0-0.dll'),
('C:/WINDOWS/WinSxS/amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.19041.1288_none_91a663c8cc864906/gdiplus.dll', 'gdiplus.dll'),
('C:/msys64/mingw64/bin/libgdk-3-0.dll', 'libgdk-3-0.dll'),
('C:/WINDOWS/System32/SETUPAPI.dll', 'SETUPAPI.dll'),
('C:/WINDOWS/System32/cfgmgr32.dll', 'cfgmgr32.dll'),
('C:/WINDOWS/SYSTEM32/dwmapi.dll', 'dwmapi.dll'),
('C:/msys64/mingw64/bin/libepoxy-0.dll', 'libepoxy-0.dll'),
('C:/msys64/mingw64/bin/libpangowin32-1.0-0.dll', 'libpangowin32-1.0-0.dll'),
('C:/msys64/mingw64/bin/libpangocairo-1.0-0.dll', 'libpangocairo-1.0-0.dll'),
('C:/WINDOWS/SYSTEM32/WINMM.dll', 'WINMM.dll'),
('C:/msys64/mingw64/bin/libpangoft2-1.0-0.dll', 'libpangoft2-1.0-0.dll'),
('C:/WINDOWS/system32/uxtheme.dll', 'uxtheme.dll'),
('C:/WINDOWS/System32/shcore.dll', 'shcore.dll'),
('C:/WINDOWS/System32/MSCTF.dll', 'MSCTF.dll'),
('C:/WINDOWS/System32/OLEAUT32.dll', 'OLEAUT32.dll'),
('C:/WINDOWS/SYSTEM32/DEVOBJ.dll', 'DEVOBJ.dll'),
('C:/WINDOWS/System32/WINTRUST.dll', 'WINTRUST.dll'),
('C:/WINDOWS/System32/CRYPT32.dll', 'CRYPT32.dll'),
('C:/WINDOWS/SYSTEM32/MSASN1.dll', 'MSASN1.dll'),
('C:/WINDOWS/SYSTEM32/kernel.appcore.dll', 'kernel.appcore.dll'),
('C:/WINDOWS/System32/clbcatq.dll', 'clbcatq.dll'),
('C:/msys64/mingw64/bin/libgtk-3-0.dll', 'libgtk-3-0.dll'),
('C:/WINDOWS/System32/comdlg32.dll', 'comdlg32.dll'),
('C:/WINDOWS/WinSxS/amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.1110_none_60b5254171f9507e/COMCTL32.dll', 'COMCTL32.dll'),
('C:/msys64/mingw64/bin/libatk-1.0-0.dll', 'libatk-1.0-0.dll'),
(' C:/msys64/mingw64/bin/libopenblas.dll', 'libopenblas.dll'),
('C:/msys64/mingw64/bin/libgfortran-5.dll', 'libgfortran-5.dll'),
('C:/msys64/mingw64/bin/libquadmath-0.dll', 'libquadmath-0.dll'),
('C:/Windows/System32/AppXDeploymentClient.dll', 'AppXDeploymentClient.dll'),
('C:/Windows/System32/Windows.ApplicationModel.dll', 'Windows.ApplicationModel.dll'),
('C:/Windows/System32/twinapi.appcore.dll', 'twinapi.appcore.dll'),
('C:/WINDOWS/SYSTEM32/windows.storage.dll', 'windows.storage.dll'),
('C:/Windows/System32/Wldp.dll', 'Wldp.dll'),
('C:/WINDOWS/system32/propsys.dll', 'propsys.dll'),
('C:/WINDOWS/SYSTEM32/profapi.dll', 'profapi.dll'),
('C:/WINDOWS/system32/mssprxy.dll', 'mssprxy.dll'),
('C:/Program Files/Git/mingw64/bin/libcrypto-1_1-x64.dll', 'libcrypto-1_1-x64.dll'),
('C:/msys64/mingw64/bin/imagequant.dll', 'imagequant.dll'),
('C:/msys64/mingw64/bin/libtiff-5.dll', 'libtiff-5.dll'),
('C:/msys64/mingw64/bin/libopenjp2-7.dll', 'libopenjp2-7.dll'),
('C:/msys64/mingw64/bin/libjpeg-8.dll', 'libjpeg-8.dll'),
('C:/msys64/mingw64/bin/libjbig-0.dll', 'libjbig-0.dll'),
('C:/Users/PICHAU/anaconda3/Library/bin/libdeflate.dll', 'libdeflate.dll'),
('C:/msys64/mingw64/bin/libLerc.dll', 'libLerc.dll'),
('C:/WINDOWS/SYSTEM32/VCRUNTIME140.dll', 'VCRUNTIME140.dll'),
('C:/Program Files/Git/mingw64/bin/libzstd.dll', 'libzstd.dll'),
('C:/msys64/mingw64/bin/libwebp-7.dll', 'libwebp-7.dll'),
('C:/WINDOWS/system32/IconCodecService.dll', 'IconCodecService.dll'),
('C:/WINDOWS/SYSTEM32/WindowsCodecs.dll', 'WindowsCodecs.dll'),
('C:/WINDOWS/SYSTEM32/mrmcorer.dll', 'mrmcorer.dll'),
('C:/WINDOWS/SYSTEM32/iertutil.dll', 'iertutil.dll'),
('C:/WINDOWS/SYSTEM32/windows.staterepositorycore.dll', 'windows.staterepositorycore.dll'),
('C:/WINDOWS/SYSTEM32/bcp47mrm.dll', 'bcp47mrm.dll'),
('C:/Windows/System32/Windows.UI.dll', 'Windows.UI.dll'),
('C:/Windows/System32/InputHost.dll', 'InputHost.dll'),
('C:/Windows/System32/TextInputFramework.dll', 'TextInputFramework.dll'),
('C:/Windows/System32/WindowManagementAPI.dll', 'WindowManagementAPI.dll'),
('C:/Windows/System32/CoreMessaging.dll', 'CoreMessaging.dll'),
('C:/Windows/System32/CoreUIComponents.dll', 'CoreUIComponents.dll'),
('C:/WINDOWS/SYSTEM32/wintypes.dll', 'wintypes.dll'),
('C:/WINDOWS/SYSTEM32/ntmarta.dll', 'ntmarta.dll'),
('C:/WINDOWS/system32/winhttp.dll', 'winhttp.dll'),
('C:/msys64/mingw64/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-jpeg.dll', 'libpixbufloader-jpeg.dll'),
('C:/msys64/mingw64/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.dll', 'libpixbufloader-svg.dll'),
('C:/msys64/mingw64/bin/librsvg-2-2.dll', 'librsvg-2-2.dll'),
('C:/msys64/mingw64/bin/libxml2-2.dll', 'libxml2-2.dll'),
('C:/WINDOWS/SYSTEM32/USERENV.dll', 'USERENV.dll'),
('C:/msys64/mingw64/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.dll', 'libpixbufloader-png.dll'),
('C:/WINDOWS/SYSTEM32/mscms.dll', 'mscms.dll'),
('C:/WINDOWS/SYSTEM32/ColorAdapterClient.dll', 'ColorAdapterClient.dll'),
('C:/WINDOWS/SYSTEM32/icm32.dll', 'icm32.dll'),
('C:/WINDOWS/system32/mswsock.dl', 'mswsock.dll'),
# Bibliotecas necessárias 
('C:/msys64/mingw64/lib/girepository-1.0', 'lib/girepository-1.0'),
('C:/msys64/mingw64/lib/gtk-3.0', 'lib/gtk-3.0'),
('C:/msys64/mingw64/lib/gdk-pixbuf-2.0', 'lib/gdk-pixbuf-2.0'),
('C:/msys64/mingw64/share/glib-2.0', 'share/glib-2.0'),
# Arquivos estáticos
('projeto_feira.glade')
]